"""
HTML 导出器
============

导出可视化的 HTML 格式报告

严格遵循 docs/design/02_概要设计文档_v1.0.md 的技术栈要求
"""

import logging
from typing import Optional

from nova_executor.report.types import Report, ExportFormat
from nova_executor.report.exporters.base import Exporter

logger = logging.getLogger(__name__)


class HtmlExporter(Exporter):
    """
    HTML 导出器

    生成可读的 HTML 报告
    """

    HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>测试报告 - {instance_id}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-bottom: 20px;
        }}
        .metric {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
            color: #667eea;
        }}
        .metric-label {{
            color: #666;
            font-size: 0.9em;
            margin-top: 5px;
        }}
        .steps {{
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .step {{
            border-left: 3px solid #667eea;
            padding: 15px;
            margin: 10px 0;
            background: #f9f9f9;
            border-radius: 4px;
        }}
        .step-success {{ border-left-color: #48bb78; }}
        .step-failure {{ border-left-color: #f56565; background: #fff5f5; }}
        .step-hil {{ border-left-color: #ed8936; background: #fffaf0; }}
        .defect {{
            background: #fff5f5;
            border: 1px solid #f56565;
            padding: 10px;
            margin: 5px 0;
            border-radius: 4px;
        }}
        .critical {{ color: #c53030; font-weight: bold; }}
        .high {{ color: #dd6b20; }}
        .medium {{ color: #d69e2e; }}
        .low {{ color: #38a169; }}
        .footer {{
            text-align: center;
            color: #999;
            margin-top: 20px;
            padding: 20px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>测试执行报告</h1>
        <p>实例ID: {instance_id}</p>
        <p>任务ID: {task_id}</p>
        <p>生成时间: {created_at}</p>
    </div>

    <div class="summary">
        <div class="metric">
            <div class="metric-value">{total_steps}</div>
            <div class="metric-label">总步骤</div>
        </div>
        <div class="metric">
            <div class="metric-value">{success_rate}%</div>
            <div class="metric-label">成功率</div>
        </div>
        <div class="metric">
            <div class="metric-value">{total_defects}</div>
            <div class="metric-label">缺陷数</div>
        </div>
        <div class="metric">
            <div class="metric-value">{hil_count}</div>
            <div class="metric-label">HIL 介入</div>
        </div>
        <div class="metric">
            <div class="metric-value">{duration}s</div>
            <div class="metric-label">执行时长</div>
        </div>
    </div>

    {defects_section}

    <div class="steps">
        <h2>执行步骤</h2>
        {steps_html}
    </div>

    <div class="footer">
        <p>Generated by Nova Test AaaS Executor v1.0.0</p>
    </div>
</body>
</html>"""

    def get_format(self) -> ExportFormat:
        return ExportFormat.HTML

    async def export(self, report: Report) -> bytes:
        """
        导出 HTML 格式报告

        Args:
            report: 报告对象

        Returns:
            HTML 字节数据
        """
        logger.info(f"[HtmlExporter] 导出报告: {report.report_id}")

        # 生成步骤 HTML
        steps_html = self._generate_steps_html(report)

        # 生成缺陷 HTML
        defects_html = self._generate_defects_html(report)

        # 填充模板
        html = self.HTML_TEMPLATE.format(
            instance_id=report.instance_id,
            task_id=report.task_id,
            created_at=report.created_at,
            total_steps=report.summary.total_steps,
            success_rate=int(report.summary.success_rate * 100),
            total_defects=report.summary.total_defects,
            hil_count=report.summary.hil_count,
            duration=int(report.summary.execution_duration_seconds),
            steps_html=steps_html,
            defects_section=defects_html,
        )

        # 脱敏处理
        html = self.mask_sensitive_data(html)

        return html.encode("utf-8")

    def _generate_steps_html(self, report: Report) -> str:
        """生成步骤 HTML"""
        steps = []
        for step in report.steps:
            status_class = "step-success"
            if step.error:
                status_class = "step-failure"

            steps.append(f"""
            <div class="step {status_class}">
                <strong>步骤 {step.step_number}</strong> - {step.node_name}
                {f'<br>动作: {step.action_type}' if step.action_type else ''}
                {f'<br>置信度: {step.confidence}' if step.confidence else ''}
                {f'<br><span style="color:red">错误: {step.error}</span>' if step.error else ''}
            </div>
            """)

        return "\n".join(steps) if steps else "<p>无步骤记录</p>"

    def _generate_defects_html(self, report: Report) -> str:
        """生成缺陷 HTML"""
        if not report.defects:
            return ""

        defects = []
        for defect in report.defects:
            severity_class = defect.get("severity", "MEDIUM").lower()
            defects.append(f"""
            <div class="defect {severity_class}">
                <strong class="{severity_class}">{defect.get("severity", "MEDIUM")}</strong>
                步骤 {defect.get("step_number", "?")}:
                {defect.get("error_type", "unknown")} - {defect.get("error_message", "无描述")}
            </div>
            """)

        return f"""
        <div class="defects-section">
            <h2>缺陷列表 ({len(report.defects)})</h2>
            {"".join(defects)}
        </div>
        """
